services:
  - type: web
    name: texsync-backend
    env: node
    region: oregon
    buildCommand: |
      cd server
      npm install
      # Install LaTeX packages
      apt-get update
      apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-xetex texlive-luatex
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    disk:
      name: texsync-latex-temp
      mountPath: /opt/render/project/src/server/temp
      sizeGB: 2

databases:
  - name: texsync-db
    databaseName: texsync
    user: texsync
    region: oregon
