services:
  - type: web
    name: texsync-backend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile.render
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health