export const latexCommands = [
  { label: "\\begin", detail: "Start environment" },
  { label: "\\end", detail: "End environment" },
  { label: "\\section", detail: "Section heading" },
  { label: "\\subsection", detail: "Subsection heading" },
  { label: "\\textbf", detail: "Bold text" },
  { label: "\\textit", detail: "Italic text" },
  { label: "\\underline", detail: "Underlined text" },
  { label: "\\cite", detail: "Citation" },
  { label: "\\label", detail: "Create a label" },
  { label: "\\ref", detail: "Reference a label" },
  { label: "\\includegraphics", detail: "Insert image" },
  { label: "\\documentclass", detail: "Document class declaration" },
  { label: "\\usepackage", detail: "Load a package" },
  { label: "\\item", detail: "List item" },
  { label: "\\mathbf", detail: "Bold math symbol" },
  { label: "\\mathit", detail: "Italic math symbol" },
  { label: "\\mathrm", detail: "Roman math symbol" },
  { label: "\\frac", detail: "Fraction" },
  { label: "\\sqrt", detail: "Square root" },
  { label: "\\sum", detail: "Summation symbol" },
  { label: "\\int", detail: "Integral symbol" },
  { label: "\\infty", detail: "Infinity symbol" },
  { label: "\\partial", detail: "Partial derivative" },
  { label: "\\nabla", detail: "Nabla/Del operator" },
  { label: "\\alpha", detail: "Greek letter alpha" },
  { label: "\\beta", detail: "Greek letter beta" },
  { label: "\\gamma", detail: "Greek letter gamma" },
  { label: "\\delta", detail: "Greek letter delta" },
  { label: "\\epsilon", detail: "Greek letter epsilon" },
  { label: "\\theta", detail: "Greek letter theta" },
  { label: "\\lambda", detail: "Greek letter lambda" },
  { label: "\\mu", detail: "Greek letter mu" },
  { label: "\\pi", detail: "Greek letter pi" },
  { label: "\\sigma", detail: "Greek letter sigma" },
  { label: "\\omega", detail: "Greek letter omega" }
];